### ISSUE TITLE
-Dmaven.multiModuleProjectDirectory system property is not set

### ISSUE THREAD

**Issue by imshubhangi** [hortonworks/hive-testbench#11]
While compiling and packaging the data generator for tpch following error is seen. 

`
./tpch-build.sh `
`...`
`-Dmaven.multiModuleProjectDirectory system property is not set.make: *** [target/tpch-gen-1.0-SNAPSHOT.jar] Error 1`

**Comment by imshubhangi** [comment]
Issue resolved after setting M2_HOME as appropriate.

**Comment by BradySuen** [comment]
hello ,how to set this property correctly? what is the true value?
