### ISSUE TITLE
FAILED: SemanticException [Error 10249]: Line 20:16 Unsupported SubQuery Expression 'cr_order_number': Only 1 SubQuery expression is supported.

### ISSUE THREAD

**Issue by gdchaochao** [hortonworks/hive-testbench#12]
query10, query16..
FAILED: SemanticException [Error 10249]: Line 20:16 Unsupported SubQuery Expression 'cr_order_number': Only 1 SubQuery expression is supported.

**Comment by WookieGao** [comment]
same prob with sample-queries-tpcds/query6.sql   

  any solutions?

**Comment by gdchaochao** [comment]
@WookieGao 
for hive:
`  set hive.mapred.mode=nonstrict;
  set hive.strict.checks.cartesian.product=false;`
for spark
`set spark.sql.crossJoin.enabled=true;`
it work for me
