### ISSUE TITLE
Table not found 'date_dim'

### ISSUE THREAD

**Issue by mave89** [hortonworks/hive-testbench#4]
While generating tpcds data, I got a make error. When "export DEBUG_SCRIPT=X" was set, it gave a little more detailed error as below. Anyone knows what's going on? 

jdbc:hive2://localhost:2181/> create table date_dim
jdbc:hive2://localhost:2181/> stored as ${FILE}
jdbc:hive2://localhost:2181/> as select * from ${SOURCE}.date_dim;
Error: Error while compiling statement: FAILED: SemanticException [Error 10001]: Line 3:17 Table not found 'date_dim' (state=42S02,code=10001)

Closing: 0: jdbc:hive2://localhost:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2?tez.queue.name=default
make: *** [date_dim] Error 2

**Comment by mave89** [comment]
Answering my own question, it was a permissions error. But weird that it would give me the above, cryptic error.

Fix that worked for me:
hadoop fs -chown -R hive:hadoop /tmp

**Comment by qcsea** [comment]
I I also encountered this problem, chown -R 777 is still not working.
